import 'package:events/features/model/event.dart';

final List<String> categories = [
  'all',
  'art',
  'tech',
  'design',
  'movies',
  'business',
];

List<Event> generateEvents = const [
  Event(
    image: 'assets/imgs/city/st_petersburg.jpg',
    startDate: "15 jun 2023",
    endDate: '16 jun 2023',
    name: 'DevOpsDay Birmingham 2023',
    location: 'Saint-Petersburg',
    cost: '2400',
    discountCost: null,
  ),
  Event(
    image: 'assets/imgs/city/moscow.jpg',
    startDate: "20 jun 2023",
    endDate: '22 jun 2023',
    name: 'Flutter Conference',
    location: 'Moscow',
    cost: '1500',
    discountCost: '120',
  ),
  Event(
    image: 'assets/imgs/city/kazan.jpg',
    startDate: "25 feb 2023",
    endDate: '26 feb 2023',
    name: 'AI Summit',
    location: 'Kazan',
    cost: '3000',
    discountCost: '250',
  ),
  Event(
    image: 'assets/imgs/city/nizhny_novgorod.jpg',
    startDate: "5 march 2023",
    endDate: null,
    name: 'Web Development Summit',
    location: 'Nizhny Novgorod',
    cost: '1800',
    discountCost: '150',
  ),
  Event(
    image: 'assets/imgs/city/ekaterinburg.jpg',
    startDate: "10 jul 2023",
    endDate: '12 jul 2023',
    name: 'Data Science Expo',
    location: 'Ekaterinburg',
    cost: '2800',
    discountCost: null,
  ),
  Event(
    image: 'assets/imgs/city/kaliningrad.jpg',
    startDate: "25 jul 2023",
    endDate: '27 jul 2023',
    name: 'Mobile App Workshop',
    location: 'Kaliningrad',
    cost: '1200',
    discountCost: '90',
  ),
  Event(
    image: 'assets/imgs/city/arkhangelsk.jpg',
    startDate: "20 aug 2023",
    endDate: '22 aug 2023',
    name: 'Blockchain Summit',
    location: 'Arkhangelsk',
    cost: '3200',
    discountCost: '280',
  ),
  Event(
    image: 'assets/imgs/city/sochi.jpg',
    startDate: "25 aprl 2023",
    endDate: '27 aprl 2023',
    name: 'UX/UI Design Conference',
    location: 'Soshi',
    cost: '2000',
    discountCost: null,
  ),
];
